[package]
license = "Apache-2.0"
name = "kimix-tools-api"
version.workspace = true
edition.workspace = true
description = "Protobuf API definitions for Kimix tools"

[dependencies]
tonic-prost = { workspace = true }
# Protobuf runtime
prost = { workspace = true }
tonic = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
kimix-tool-protocol = { workspace = true }

[build-dependencies]
kimix-proto-build = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["serde", "tonic"]

[lints]
workspace = true
